# Generated by Django 3.0.2 on 2020-01-11 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20200110_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='category',
            new_name='category_id',
        ),
    ]
