# Generated by Django 3.0.2 on 2020-01-11 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_auto_20200111_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='category_id',
            new_name='category',
        ),
    ]
